/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSubmitTopicRouteImport } from './routes/_app/submit-topic'
import { Route as AppYourSubmissionsRouteImport } from './routes/_app/your-submissions'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppAdminLeaderboardRouteImport } from './routes/_app/admin/leaderboard'
import { Route as AppAdminSubmissionsRouteImport } from './routes/_app/admin/submissions'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSubmitTopicRoute = AppSubmitTopicRouteImport.update({
  id: '/submit-topic',
  path: '/submit-topic',
  getParentRoute: () => AppRoute,
} as any)
const AppYourSubmissionsRoute = AppYourSubmissionsRouteImport.update({
  id: '/your-submissions',
  path: '/your-submissions',
  getParentRoute: () => AppRoute,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminLeaderboardRoute = AppAdminLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSubmissionsRoute = AppAdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/submit-topic': typeof AppSubmitTopicRoute
  '/your-submissions': typeof AppYourSubmissionsRoute
  '/api/og': typeof ApiOgRoute
  '/admin/leaderboard': typeof AppAdminLeaderboardRoute
  '/admin/submissions': typeof AppAdminSubmissionsRoute
  '/admin/': typeof AppAdminIndexRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof AppSettingsRoute
  '/submit-topic': typeof AppSubmitTopicRoute
  '/your-submissions': typeof AppYourSubmissionsRoute
  '/api/og': typeof ApiOgRoute
  '/': typeof AppIndexRoute
  '/admin/leaderboard': typeof AppAdminLeaderboardRoute
  '/admin/submissions': typeof AppAdminSubmissionsRoute
  '/admin': typeof AppAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/submit-topic': typeof AppSubmitTopicRoute
  '/_app/your-submissions': typeof AppYourSubmissionsRoute
  '/api/og': typeof ApiOgRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/leaderboard': typeof AppAdminLeaderboardRoute
  '/_app/admin/submissions': typeof AppAdminSubmissionsRoute
  '/_app/admin/': typeof AppAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/admin'
    | '/settings'
    | '/submit-topic'
    | '/your-submissions'
    | '/api/og'
    | '/admin/leaderboard'
    | '/admin/submissions'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/settings'
    | '/submit-topic'
    | '/your-submissions'
    | '/api/og'
    | '/'
    | '/admin/leaderboard'
    | '/admin/submissions'
    | '/admin'
  id:
    | '__root__'
    | '/_app'
    | '/onboarding'
    | '/_app/admin'
    | '/_app/settings'
    | '/_app/submit-topic'
    | '/_app/your-submissions'
    | '/api/og'
    | '/_app/'
    | '/_app/admin/leaderboard'
    | '/_app/admin/submissions'
    | '/_app/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  ApiOgRoute: typeof ApiOgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/submit-topic': {
      id: '/_app/submit-topic'
      path: '/submit-topic'
      fullPath: '/submit-topic'
      preLoaderRoute: typeof AppSubmitTopicRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/your-submissions': {
      id: '/_app/your-submissions'
      path: '/your-submissions'
      fullPath: '/your-submissions'
      preLoaderRoute: typeof AppYourSubmissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/leaderboard': {
      id: '/_app/admin/leaderboard'
      path: '/leaderboard'
      fullPath: '/admin/leaderboard'
      preLoaderRoute: typeof AppAdminLeaderboardRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/submissions': {
      id: '/_app/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AppAdminSubmissionsRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminLeaderboardRoute: typeof AppAdminLeaderboardRoute
  AppAdminSubmissionsRoute: typeof AppAdminSubmissionsRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminLeaderboardRoute: AppAdminLeaderboardRoute,
  AppAdminSubmissionsRoute: AppAdminSubmissionsRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubmitTopicRoute: typeof AppSubmitTopicRoute
  AppYourSubmissionsRoute: typeof AppYourSubmissionsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppSubmitTopicRoute: AppSubmitTopicRoute,
  AppYourSubmissionsRoute: AppYourSubmissionsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  ApiOgRoute: ApiOgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
