/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppFeedbackRouteImport } from './routes/_app/feedback'
import { Route as AppSubmitTopicRouteImport } from './routes/_app/submit-topic'
import { Route as AppUserSettingsRouteImport } from './routes/_app/userSettings'
import { Route as AppYourSubmissionsRouteImport } from './routes/_app/yourSubmissions'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppAdminFeedbackRouteImport } from './routes/_app/admin/feedback'
import { Route as AppAdminLeaderboardManagementRouteImport } from './routes/_app/admin/leaderboardManagement'
import { Route as AppAdminNewUsersRouteImport } from './routes/_app/admin/newUsers'
import { Route as AppAdminSubmissionsRouteImport } from './routes/_app/admin/submissions'
import { Route as AppAdminUserManagementRouteImport } from './routes/_app/admin/userManagement'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppSubmitTopicRoute = AppSubmitTopicRouteImport.update({
  id: '/submit-topic',
  path: '/submit-topic',
  getParentRoute: () => AppRoute,
} as any)
const AppUserSettingsRoute = AppUserSettingsRouteImport.update({
  id: '/userSettings',
  path: '/userSettings',
  getParentRoute: () => AppRoute,
} as any)
const AppYourSubmissionsRoute = AppYourSubmissionsRouteImport.update({
  id: '/yourSubmissions',
  path: '/yourSubmissions',
  getParentRoute: () => AppRoute,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminFeedbackRoute = AppAdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminLeaderboardManagementRoute =
  AppAdminLeaderboardManagementRouteImport.update({
    id: '/leaderboardManagement',
    path: '/leaderboardManagement',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminNewUsersRoute = AppAdminNewUsersRouteImport.update({
  id: '/newUsers',
  path: '/newUsers',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSubmissionsRoute = AppAdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUserManagementRoute = AppAdminUserManagementRouteImport.update({
  id: '/userManagement',
  path: '/userManagement',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/feedback': typeof AppFeedbackRoute
  '/submit-topic': typeof AppSubmitTopicRoute
  '/userSettings': typeof AppUserSettingsRoute
  '/yourSubmissions': typeof AppYourSubmissionsRoute
  '/api/og': typeof ApiOgRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/admin/feedback': typeof AppAdminFeedbackRoute
  '/admin/leaderboardManagement': typeof AppAdminLeaderboardManagementRoute
  '/admin/newUsers': typeof AppAdminNewUsersRoute
  '/admin/submissions': typeof AppAdminSubmissionsRoute
  '/admin/userManagement': typeof AppAdminUserManagementRoute
  '/admin/': typeof AppAdminIndexRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof OnboardingRoute
  '/feedback': typeof AppFeedbackRoute
  '/submit-topic': typeof AppSubmitTopicRoute
  '/userSettings': typeof AppUserSettingsRoute
  '/yourSubmissions': typeof AppYourSubmissionsRoute
  '/api/og': typeof ApiOgRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/': typeof AppIndexRoute
  '/admin/feedback': typeof AppAdminFeedbackRoute
  '/admin/leaderboardManagement': typeof AppAdminLeaderboardManagementRoute
  '/admin/newUsers': typeof AppAdminNewUsersRoute
  '/admin/submissions': typeof AppAdminSubmissionsRoute
  '/admin/userManagement': typeof AppAdminUserManagementRoute
  '/admin': typeof AppAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/feedback': typeof AppFeedbackRoute
  '/_app/submit-topic': typeof AppSubmitTopicRoute
  '/_app/userSettings': typeof AppUserSettingsRoute
  '/_app/yourSubmissions': typeof AppYourSubmissionsRoute
  '/api/og': typeof ApiOgRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/feedback': typeof AppAdminFeedbackRoute
  '/_app/admin/leaderboardManagement': typeof AppAdminLeaderboardManagementRoute
  '/_app/admin/newUsers': typeof AppAdminNewUsersRoute
  '/_app/admin/submissions': typeof AppAdminSubmissionsRoute
  '/_app/admin/userManagement': typeof AppAdminUserManagementRoute
  '/_app/admin/': typeof AppAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/admin'
    | '/feedback'
    | '/submit-topic'
    | '/userSettings'
    | '/yourSubmissions'
    | '/api/og'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin/feedback'
    | '/admin/leaderboardManagement'
    | '/admin/newUsers'
    | '/admin/submissions'
    | '/admin/userManagement'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/feedback'
    | '/submit-topic'
    | '/userSettings'
    | '/yourSubmissions'
    | '/api/og'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/'
    | '/admin/feedback'
    | '/admin/leaderboardManagement'
    | '/admin/newUsers'
    | '/admin/submissions'
    | '/admin/userManagement'
    | '/admin'
  id:
    | '__root__'
    | '/_app'
    | '/onboarding'
    | '/_app/admin'
    | '/_app/feedback'
    | '/_app/submit-topic'
    | '/_app/userSettings'
    | '/_app/yourSubmissions'
    | '/api/og'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/_app/'
    | '/_app/admin/feedback'
    | '/_app/admin/leaderboardManagement'
    | '/_app/admin/newUsers'
    | '/_app/admin/submissions'
    | '/_app/admin/userManagement'
    | '/_app/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  ApiOgRoute: typeof ApiOgRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feedback': {
      id: '/_app/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/submit-topic': {
      id: '/_app/submit-topic'
      path: '/submit-topic'
      fullPath: '/submit-topic'
      preLoaderRoute: typeof AppSubmitTopicRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/userSettings': {
      id: '/_app/userSettings'
      path: '/userSettings'
      fullPath: '/userSettings'
      preLoaderRoute: typeof AppUserSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/yourSubmissions': {
      id: '/_app/yourSubmissions'
      path: '/yourSubmissions'
      fullPath: '/yourSubmissions'
      preLoaderRoute: typeof AppYourSubmissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/feedback': {
      id: '/_app/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AppAdminFeedbackRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/leaderboardManagement': {
      id: '/_app/admin/leaderboardManagement'
      path: '/leaderboardManagement'
      fullPath: '/admin/leaderboardManagement'
      preLoaderRoute: typeof AppAdminLeaderboardManagementRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/newUsers': {
      id: '/_app/admin/newUsers'
      path: '/newUsers'
      fullPath: '/admin/newUsers'
      preLoaderRoute: typeof AppAdminNewUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/submissions': {
      id: '/_app/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AppAdminSubmissionsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/userManagement': {
      id: '/_app/admin/userManagement'
      path: '/userManagement'
      fullPath: '/admin/userManagement'
      preLoaderRoute: typeof AppAdminUserManagementRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminFeedbackRoute: typeof AppAdminFeedbackRoute
  AppAdminLeaderboardManagementRoute: typeof AppAdminLeaderboardManagementRoute
  AppAdminNewUsersRoute: typeof AppAdminNewUsersRoute
  AppAdminSubmissionsRoute: typeof AppAdminSubmissionsRoute
  AppAdminUserManagementRoute: typeof AppAdminUserManagementRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminFeedbackRoute: AppAdminFeedbackRoute,
  AppAdminLeaderboardManagementRoute: AppAdminLeaderboardManagementRoute,
  AppAdminNewUsersRoute: AppAdminNewUsersRoute,
  AppAdminSubmissionsRoute: AppAdminSubmissionsRoute,
  AppAdminUserManagementRoute: AppAdminUserManagementRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppSubmitTopicRoute: typeof AppSubmitTopicRoute
  AppUserSettingsRoute: typeof AppUserSettingsRoute
  AppYourSubmissionsRoute: typeof AppYourSubmissionsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppFeedbackRoute: AppFeedbackRoute,
  AppSubmitTopicRoute: AppSubmitTopicRoute,
  AppUserSettingsRoute: AppUserSettingsRoute,
  AppYourSubmissionsRoute: AppYourSubmissionsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  ApiOgRoute: ApiOgRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
